alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

name: portfolio
region: blr

static_sites:
  - name: portfolio
    github:
      branch: production
      deploy_on_push: true
      repo: theoctacoder/portfolio
    build_command: flutter build web --release
    output_dir: build/web
    source_dir: /
    catchall_document: index.html
    environment_variables:
      - key: FLUTTER_VERSION
        value: "3.27.4"
